services:
  app:
    image: ${DOCKER_USER}/team-profile-api:${IMAGE_TAG}
    container_name: team-profile-api
    network_mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=ap-northeast-2
    restart: unless-stopped